import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LiveVisualEditing from "../components/LiveVisualEditing";
import { draftMode } from "next/headers";
import { ThemeProvider } from "../components/global/ThemeProvider";
import ProviderWrapper from "../components/global/ProviderWrapper";
import { loadQuery } from "../sanity/lib/store";
import { SanityDocument } from "next-sanity";
import { NAVIGATION } from "../sanity/lib/client";
import Header from "../components/navigations/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

    const navigation = await loadQuery<SanityDocument[]>(NAVIGATION, {}, {
    cache: "no-store"
    });
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <Header navigation={navigation.data} />
          <ProviderWrapper>
            {children}
          </ProviderWrapper>
          {draftMode().isEnabled && <LiveVisualEditing />}
       </ThemeProvider>
      </body>
    </html>
  );
}
